= Ryan's AVA Testing Organization Style
Ryan Leonard
:ava: AVA
:ava-link: https://github.com/avajs/ava
:aval: link:{ava-link}[{ava}]
:ava-assertions: link:https://github.com/avajs/ava#assertions[assertions]
:mocha: Mocha
:mochal: link:https://mochajs.org/[{mocha}]
:chai: Chai
:chail: link:http://chaijs.com/[{chai}]
:guide-link-title: Ryan's AVA Test Style
:guide-link: https://github.com/CodeLenny/ava-test-style
:guide-badge: https://img.shields.io/badge/AVA%20Test%20Style-@CodeLenny-blue.svg
:toc: preamble

{aval} is a powerful testing platform that I've been using in most of my repositories instead of {mochal}.
After trying out {ava} in many repositories, I've started to settle into a standard style that works well for creating
clean, understandable, and simple testing files.

This document attempts to record my current style for writing {ava} tests.
Some of my style is intuitive to {ava},
like using the built-in {ava-assertions} instead of external assertion libraries like {chail},
but other stylistic decisions are my own.

This guide is intended to serve as a reference for libraries that follow my style choices.
If you have differing style choices to mine, feel free to fork this style guide and tweak to your liking.
You can also submit issues or pull requests and discuss pros and cons to different choices, and I may tweak my style if
convinced that another way is better.

.Embedable Badge image:{guide-badge}[]
[source,md,subs="attributes"]
----
[![AVA Test Style Guide]({guide-badge})]({guide-link})
----

.Text Reference
[source,md,subs="attributes"]
----
This module is tested using [{ava}]({ava-link}).
Tests should conform to [{guide-link-title}]({guide-link}).
----

== Highlights

- Tests are code, and should conform to lint rules.
- The file-system reflects the organization of tests.
- Unit tests are separated from integration tests.
- Put all setup in `before`/`beforeEach` statements.
- Use built-in test organization messages over inline comments or `README` descriptions when possible.
